bot/urls.py
from django.urls import path

from bot.views import UserProfileView, ChallengeView

urlpatterns = [
    path('profile/<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('challenge/<int:challenge_id>', ChallengeView.as_view(), name='challenge'),
]

creatives_discord_bot/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bot.urls'))
]

bot/models.py
from asgiref.sync import sync_to_async
from django.db import models
from django.utils import timezone
from django.utils.html import format_html

from bot.async_utils import AsyncModel
from creatives_discord_bot.settings import IMAGES_URL


class User(AsyncModel):
    discord_id = models.BigIntegerField(primary_key=True)
    display_name = models.CharField(max_length=256)
    avatar_url = models.URLField(null=True, blank=True)
    registered = models.DateField(auto_now=True)
    lives = models.IntegerField(default=3)

    def get_score(self) -> int:
        return sum(s.get_score() for s in self.submission_set.all())

    @property
    def mention(self) -> str:
        return f'<@{self.discord_id}>'

    def get_lives_string(self) -> str:
        return '♥️' * self.lives + '♡' * (3 - self.lives)

    def __str__(self):
        return f'{self.display_name} ({self.discord_id})'

    def __repr__(self):
        return f'{self.display_name} ({self.discord_id})'


class Challenge(AsyncModel):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    start = models.DateTimeField()
    deadline = models.DateTimeField()

    class NoCurrentChallenge(Exception):
        pass

    @staticmethod
    def get_current() -> 'Challenge':
        now = timezone.now()
        try:
            return Challenge.objects.get(start__lte=now, deadline__gt=now)
        except Challenge.DoesNotExist:
            raise Challenge.NoCurrentChallenge()

    @staticmethod
    async def aget_current() -> 'Challenge':
        return await sync_to_async(Challenge.get_current)()

    def __str__(self):
        return f'{self.title} ({self.deadline:%d %b %H:%M})'

    def __repr__(self):
        return f'{self.title} ({self.deadline:%d %b %H:%M})'


class InspirationImage(AsyncModel):
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=IMAGES_URL)

    def __str__(self):
        return f'{self.image} ({self.challenge.title})'

    def __repr__(self):
        return f'{self.image} ({self.challenge.title})'


class Submission(AsyncModel):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    message_id = models.BigIntegerField(null=True)
    description = models.CharField(max_length=512, null=True)
    file_url = models.URLField()
    media_type = models.CharField(max_length=128)
    submitted_time = models.DateTimeField(auto_now=True)

    INITIAL_POINTS = 50
    VOTE_POINTS = 10

    def get_html(self):
        if self.media_type.startswith('image'):
            return format_html(
                '<img src="{image_url}" width="150" height="150" style="object-fit: cover"/>',
                image_url=self.file_url
            )
        elif self.media_type.startswith('video'):
            return format_html(
                '''<video width="150" height="150" controls>
                  <source src="{video_url}" type="{media_type}">
                  </video>''',
                video_url=self.file_url,
                media_type=self.media_type
            )
        elif self.media_type.startswith('audio'):
            return format_html(
                '''<audio controls>
                  <source src="{audio_url}" type="{media_type}">
                  </audio>''',
                audio_url=self.file_url,
                media_type=self.media_type
            )
        else:
            return format_html(
                '<a href="{url}">{file_name}</a>',
                url=self.file_url,
                file_name=self.file_url.split('/')[-1]
            )

    def votes_count(self):
        return self.vote_set.count()

    def get_score(self):
        votes = self.votes_count()
        return self.INITIAL_POINTS + votes * self.VOTE_POINTS

    async def aget_score(self):
        return await sync_to_async(self.get_score)()

    def __str__(self):
        return f'Submission by {self.author} for {self.challenge.title}'

    def __repr__(self):
        return f'Submission by {self.author} for {self.challenge.title}'


class Vote(AsyncModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'submission')

bot/views.py
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import TemplateView

from bot.models import User, Challenge


class UserProfileView(TemplateView):
    template_name = "profile.html"

    def get_context_data(self, user_id, **kwargs):
        user = get_object_or_404(User, discord_id=user_id)
        return {
            'user': user,
            'lives': user.get_lives_string()
        }


class ChallengeView(TemplateView):
    template_name = "challenge.html"

    def get_context_data(self, challenge_id, **kwargs):
        challenge = get_object_or_404(Challenge, pk=challenge_id)
        if challenge.start > timezone.now():
            return {
                'error': True
            }
        return {
            'challenge': challenge
        }

bot/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    {% block style %}{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>

bot/templates/challenge.html
{% extends '_base.html' %}

{% block title %}Challenge {{ challenge.title }}{% endblock %}

{% block style %}
    <style>
        body {
            color: #c4c4c4;
            background-color: #1a1a1a
        }
    </style>
{% endblock %}

{% block content %}
    {% if error %}
        <div class="container">
            <div class="row d-flex m-3">
                <h1 class="col-6 text-right"><span>“The two most powerful warriors are patience and time.”</span></h1>
            </div>
            <div class="row d-flex m-3">
                <h2 class="col-6 text-right"><span>- Leo Tolstoy</span></h2>
            </div>
        </div>
    {% else %}

        <h1 class="text-center">{{ challenge.title }}</h1>
        <h2 class="text-center">{{ challenge.description }}</h2>


        <div class="container">
            <h2 class="text-center" style="padding-top: 50px">Inspirations</h2>
            <div class="row justify-content-center">
                {% for image in challenge.inspirationimage_set.all %}
                    <div class="col-lg-3 d-flex justify-content-center m-3">
                        <figure class="figure">
                            <a href="{{ image.image.url }}">{{ image.image.url }}</a>
                        </figure>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

bot/templates/profile.html
{% extends '_base.html' %}

{% block title %}Profile {{ user.discord_id }}{% endblock %}

{% block style %}
    <style>
        body {
            color: #c4c4c4;
            background-color: #1a1a1a
        }

        #avatar {
            max-width: 20%;
            height: auto;
        }
    </style>
{% endblock %}

{% block content %}
    <img id="avatar" class="rounded-circle mx-auto d-block m-5" src="{{ user.avatar_url }}" alt="No avatar">
    <h1 class="text-center">{{ user.display_name }}</h1>


    <div class="container">
        <div class="row justify-content-center">
            <h3 class="text-center col">Lives: {{ lives }}</h3>
            <h3 class="text-center col">Score: {{ user.get_score }}</h3>
        </div>
    </div>

    <div class="container">
        <h2 class="text-center" style="padding-top: 50px">Submissions</h2>
        <div class="row justify-content-center">
            {% for submission in user.submission_set.all %}
                <div class="col-lg-3 d-flex justify-content-center m-3">
                    <figure class="figure">
                        <a href="{{ submission.file_url }}">{{ submission.get_html }}</a>
                        <figcaption class="figure-caption">{{ submission.challenge.title }}:
                            +{{ submission.get_score }}</figcaption>
                    </figure>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}